/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodyAddProjectV1ProjectsAddPost
 */
public class BodyAddProjectV1ProjectsAddPostTest {
    private final BodyAddProjectV1ProjectsAddPost model = new BodyAddProjectV1ProjectsAddPost();

    /**
     * Model tests for BodyAddProjectV1ProjectsAddPost
     */
    @Test
    public void testBodyAddProjectV1ProjectsAddPost() {
        // TODO: test BodyAddProjectV1ProjectsAddPost
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'fromUrl'
     */
    @Test
    public void fromUrlTest() {
        // TODO: test fromUrl
    }

    /**
     * Test the property 'fromDocument'
     */
    @Test
    public void fromDocumentTest() {
        // TODO: test fromDocument
    }

    /**
     * Test the property 'defaultTitleVoiceId'
     */
    @Test
    public void defaultTitleVoiceIdTest() {
        // TODO: test defaultTitleVoiceId
    }

    /**
     * Test the property 'defaultParagraphVoiceId'
     */
    @Test
    public void defaultParagraphVoiceIdTest() {
        // TODO: test defaultParagraphVoiceId
    }

    /**
     * Test the property 'defaultModelId'
     */
    @Test
    public void defaultModelIdTest() {
        // TODO: test defaultModelId
    }

    /**
     * Test the property 'qualityPreset'
     */
    @Test
    public void qualityPresetTest() {
        // TODO: test qualityPreset
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'isbnNumber'
     */
    @Test
    public void isbnNumberTest() {
        // TODO: test isbnNumber
    }

    /**
     * Test the property 'acxVolumeNormalization'
     */
    @Test
    public void acxVolumeNormalizationTest() {
        // TODO: test acxVolumeNormalization
    }

    /**
     * Test the property 'volumeNormalization'
     */
    @Test
    public void volumeNormalizationTest() {
        // TODO: test volumeNormalization
    }

    /**
     * Test the property 'pronunciationDictionaryLocators'
     */
    @Test
    public void pronunciationDictionaryLocatorsTest() {
        // TODO: test pronunciationDictionaryLocators
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

}
