/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodyDubAVideoOrAnAudioFileV1DubbingPost
 */
public class BodyDubAVideoOrAnAudioFileV1DubbingPostTest {
    private final BodyDubAVideoOrAnAudioFileV1DubbingPost model = new BodyDubAVideoOrAnAudioFileV1DubbingPost();

    /**
     * Model tests for BodyDubAVideoOrAnAudioFileV1DubbingPost
     */
    @Test
    public void testBodyDubAVideoOrAnAudioFileV1DubbingPost() {
        // TODO: test BodyDubAVideoOrAnAudioFileV1DubbingPost
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'csvFile'
     */
    @Test
    public void csvFileTest() {
        // TODO: test csvFile
    }

    /**
     * Test the property 'foregroundAudioFile'
     */
    @Test
    public void foregroundAudioFileTest() {
        // TODO: test foregroundAudioFile
    }

    /**
     * Test the property 'backgroundAudioFile'
     */
    @Test
    public void backgroundAudioFileTest() {
        // TODO: test backgroundAudioFile
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sourceUrl'
     */
    @Test
    public void sourceUrlTest() {
        // TODO: test sourceUrl
    }

    /**
     * Test the property 'sourceLang'
     */
    @Test
    public void sourceLangTest() {
        // TODO: test sourceLang
    }

    /**
     * Test the property 'targetLang'
     */
    @Test
    public void targetLangTest() {
        // TODO: test targetLang
    }

    /**
     * Test the property 'numSpeakers'
     */
    @Test
    public void numSpeakersTest() {
        // TODO: test numSpeakers
    }

    /**
     * Test the property 'watermark'
     */
    @Test
    public void watermarkTest() {
        // TODO: test watermark
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'highestResolution'
     */
    @Test
    public void highestResolutionTest() {
        // TODO: test highestResolution
    }

    /**
     * Test the property 'dubbingStudio'
     */
    @Test
    public void dubbingStudioTest() {
        // TODO: test dubbingStudio
    }

}
