/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
 */
public class BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostTest {
    private final BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost model = new BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost();

    /**
     * Model tests for BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
     */
    @Test
    public void testBodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost() {
        // TODO: test BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
