/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PronunciationDictionaryVersionLocatorDBModel;
import com.konfigthis.client.model.VoiceSettingsResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodyTextToSpeechV1TextToSpeechVoiceIdPost
 */
public class BodyTextToSpeechV1TextToSpeechVoiceIdPostTest {
    private final BodyTextToSpeechV1TextToSpeechVoiceIdPost model = new BodyTextToSpeechV1TextToSpeechVoiceIdPost();

    /**
     * Model tests for BodyTextToSpeechV1TextToSpeechVoiceIdPost
     */
    @Test
    public void testBodyTextToSpeechV1TextToSpeechVoiceIdPost() {
        // TODO: test BodyTextToSpeechV1TextToSpeechVoiceIdPost
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'voiceSettings'
     */
    @Test
    public void voiceSettingsTest() {
        // TODO: test voiceSettings
    }

    /**
     * Test the property 'pronunciationDictionaryLocators'
     */
    @Test
    public void pronunciationDictionaryLocatorsTest() {
        // TODO: test pronunciationDictionaryLocators
    }

}
