/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost
 */
public class BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostTest {
    private final BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost model = new BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost();

    /**
     * Model tests for BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost
     */
    @Test
    public void testBodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost() {
        // TODO: test BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPost
    }

    /**
     * Test the property 'audio'
     */
    @Test
    public void audioTest() {
        // TODO: test audio
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'voiceSettings'
     */
    @Test
    public void voiceSettingsTest() {
        // TODO: test voiceSettings
    }

}
