/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ChapterStatisticsResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChapterResponseModel
 */
public class ChapterResponseModelTest {
    private final ChapterResponseModel model = new ChapterResponseModel();

    /**
     * Model tests for ChapterResponseModel
     */
    @Test
    public void testChapterResponseModel() {
        // TODO: test ChapterResponseModel
    }

    /**
     * Test the property 'chapterId'
     */
    @Test
    public void chapterIdTest() {
        // TODO: test chapterId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'lastConversionDateUnix'
     */
    @Test
    public void lastConversionDateUnixTest() {
        // TODO: test lastConversionDateUnix
    }

    /**
     * Test the property 'conversionProgress'
     */
    @Test
    public void conversionProgressTest() {
        // TODO: test conversionProgress
    }

    /**
     * Test the property 'canBeDownloaded'
     */
    @Test
    public void canBeDownloadedTest() {
        // TODO: test canBeDownloaded
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'statistics'
     */
    @Test
    public void statisticsTest() {
        // TODO: test statistics
    }

}
