/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ManualVerificationResponseModel;
import com.konfigthis.client.model.VerificationAttemptResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FineTuningResponseModel
 */
public class FineTuningResponseModelTest {
    private final FineTuningResponseModel model = new FineTuningResponseModel();

    /**
     * Model tests for FineTuningResponseModel
     */
    @Test
    public void testFineTuningResponseModel() {
        // TODO: test FineTuningResponseModel
    }

    /**
     * Test the property 'isAllowedToFineTune'
     */
    @Test
    public void isAllowedToFineTuneTest() {
        // TODO: test isAllowedToFineTune
    }

    /**
     * Test the property 'finetuningState'
     */
    @Test
    public void finetuningStateTest() {
        // TODO: test finetuningState
    }

    /**
     * Test the property 'verificationFailures'
     */
    @Test
    public void verificationFailuresTest() {
        // TODO: test verificationFailures
    }

    /**
     * Test the property 'verificationAttemptsCount'
     */
    @Test
    public void verificationAttemptsCountTest() {
        // TODO: test verificationAttemptsCount
    }

    /**
     * Test the property 'manualVerificationRequested'
     */
    @Test
    public void manualVerificationRequestedTest() {
        // TODO: test manualVerificationRequested
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'finetuningProgress'
     */
    @Test
    public void finetuningProgressTest() {
        // TODO: test finetuningProgress
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'datasetDurationSeconds'
     */
    @Test
    public void datasetDurationSecondsTest() {
        // TODO: test datasetDurationSeconds
    }

    /**
     * Test the property 'verificationAttempts'
     */
    @Test
    public void verificationAttemptsTest() {
        // TODO: test verificationAttempts
    }

    /**
     * Test the property 'sliceIds'
     */
    @Test
    public void sliceIdsTest() {
        // TODO: test sliceIds
    }

    /**
     * Test the property 'manualVerification'
     */
    @Test
    public void manualVerificationTest() {
        // TODO: test manualVerification
    }

}
