/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LibraryVoiceResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetLibraryVoicesResponseModel
 */
public class GetLibraryVoicesResponseModelTest {
    private final GetLibraryVoicesResponseModel model = new GetLibraryVoicesResponseModel();

    /**
     * Model tests for GetLibraryVoicesResponseModel
     */
    @Test
    public void testGetLibraryVoicesResponseModel() {
        // TODO: test GetLibraryVoicesResponseModel
    }

    /**
     * Test the property 'voices'
     */
    @Test
    public void voicesTest() {
        // TODO: test voices
    }

    /**
     * Test the property 'lastSortId'
     */
    @Test
    public void lastSortIdTest() {
        // TODO: test lastSortId
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    public void hasMoreTest() {
        // TODO: test hasMore
    }

}
