/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LanguageResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelResponseModel
 */
public class ModelResponseModelTest {
    private final ModelResponseModel model = new ModelResponseModel();

    /**
     * Model tests for ModelResponseModel
     */
    @Test
    public void testModelResponseModel() {
        // TODO: test ModelResponseModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'canBeFinetuned'
     */
    @Test
    public void canBeFinetunedTest() {
        // TODO: test canBeFinetuned
    }

    /**
     * Test the property 'canDoTextToSpeech'
     */
    @Test
    public void canDoTextToSpeechTest() {
        // TODO: test canDoTextToSpeech
    }

    /**
     * Test the property 'canDoVoiceConversion'
     */
    @Test
    public void canDoVoiceConversionTest() {
        // TODO: test canDoVoiceConversion
    }

    /**
     * Test the property 'canUseStyle'
     */
    @Test
    public void canUseStyleTest() {
        // TODO: test canUseStyle
    }

    /**
     * Test the property 'canUseSpeakerBoost'
     */
    @Test
    public void canUseSpeakerBoostTest() {
        // TODO: test canUseSpeakerBoost
    }

    /**
     * Test the property 'servesProVoices'
     */
    @Test
    public void servesProVoicesTest() {
        // TODO: test servesProVoices
    }

    /**
     * Test the property 'tokenCostFactor'
     */
    @Test
    public void tokenCostFactorTest() {
        // TODO: test tokenCostFactor
    }

    /**
     * Test the property 'requiresAlphaAccess'
     */
    @Test
    public void requiresAlphaAccessTest() {
        // TODO: test requiresAlphaAccess
    }

    /**
     * Test the property 'maxCharactersRequestFreeUser'
     */
    @Test
    public void maxCharactersRequestFreeUserTest() {
        // TODO: test maxCharactersRequestFreeUser
    }

    /**
     * Test the property 'maxCharactersRequestSubscribedUser'
     */
    @Test
    public void maxCharactersRequestSubscribedUserTest() {
        // TODO: test maxCharactersRequestSubscribedUser
    }

    /**
     * Test the property 'languages'
     */
    @Test
    public void languagesTest() {
        // TODO: test languages
    }

}
