/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SpeechHistoryItemResponseModel
 */
public class SpeechHistoryItemResponseModelTest {
    private final SpeechHistoryItemResponseModel model = new SpeechHistoryItemResponseModel();

    /**
     * Model tests for SpeechHistoryItemResponseModel
     */
    @Test
    public void testSpeechHistoryItemResponseModel() {
        // TODO: test SpeechHistoryItemResponseModel
    }

    /**
     * Test the property 'historyItemId'
     */
    @Test
    public void historyItemIdTest() {
        // TODO: test historyItemId
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'voiceId'
     */
    @Test
    public void voiceIdTest() {
        // TODO: test voiceId
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property 'voiceName'
     */
    @Test
    public void voiceNameTest() {
        // TODO: test voiceName
    }

    /**
     * Test the property 'voiceCategory'
     */
    @Test
    public void voiceCategoryTest() {
        // TODO: test voiceCategory
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'dateUnix'
     */
    @Test
    public void dateUnixTest() {
        // TODO: test dateUnix
    }

    /**
     * Test the property 'characterCountChangeFrom'
     */
    @Test
    public void characterCountChangeFromTest() {
        // TODO: test characterCountChangeFrom
    }

    /**
     * Test the property 'characterCountChangeTo'
     */
    @Test
    public void characterCountChangeToTest() {
        // TODO: test characterCountChangeTo
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'feedback'
     */
    @Test
    public void feedbackTest() {
        // TODO: test feedback
    }

    /**
     * Test the property 'shareLinkId'
     */
    @Test
    public void shareLinkIdTest() {
        // TODO: test shareLinkId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

}
