/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FineTuningResponseModel;
import com.konfigthis.client.model.SampleResponseModel;
import com.konfigthis.client.model.VoiceSettingsResponseModel;
import com.konfigthis.client.model.VoiceSharingResponseModel;
import com.konfigthis.client.model.VoiceVerificationResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoiceResponseModel
 */
public class VoiceResponseModelTest {
    private final VoiceResponseModel model = new VoiceResponseModel();

    /**
     * Model tests for VoiceResponseModel
     */
    @Test
    public void testVoiceResponseModel() {
        // TODO: test VoiceResponseModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'voiceId'
     */
    @Test
    public void voiceIdTest() {
        // TODO: test voiceId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'samples'
     */
    @Test
    public void samplesTest() {
        // TODO: test samples
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'fineTuning'
     */
    @Test
    public void fineTuningTest() {
        // TODO: test fineTuning
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'previewUrl'
     */
    @Test
    public void previewUrlTest() {
        // TODO: test previewUrl
    }

    /**
     * Test the property 'availableForTiers'
     */
    @Test
    public void availableForTiersTest() {
        // TODO: test availableForTiers
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'sharing'
     */
    @Test
    public void sharingTest() {
        // TODO: test sharing
    }

    /**
     * Test the property 'highQualityBaseModelIds'
     */
    @Test
    public void highQualityBaseModelIdsTest() {
        // TODO: test highQualityBaseModelIds
    }

    /**
     * Test the property 'safetyControl'
     */
    @Test
    public void safetyControlTest() {
        // TODO: test safetyControl
    }

    /**
     * Test the property 'voiceVerification'
     */
    @Test
    public void voiceVerificationTest() {
        // TODO: test voiceVerification
    }

}
