/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost {
  public static final String SERIALIZED_NAME_VANITY_SLUG = "vanity_slug";
  @SerializedName(SERIALIZED_NAME_VANITY_SLUG)
  private String vanitySlug;

  public static final String SERIALIZED_NAME_TARGET_URL = "target_url";
  @SerializedName(SERIALIZED_NAME_TARGET_URL)
  private String targetUrl;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost() {
  }

  public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost vanitySlug(String vanitySlug) {
    
    
    
    
    this.vanitySlug = vanitySlug;
    return this;
  }

   /**
   * The new slug for the vanity link. For example, if you want the vanity link to be /blog/NEW_SLUG, enter NEW_SLUG.
   * @return vanitySlug
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The new slug for the vanity link. For example, if you want the vanity link to be /blog/NEW_SLUG, enter NEW_SLUG.")

  public String getVanitySlug() {
    return vanitySlug;
  }


  public void setVanitySlug(String vanitySlug) {
    
    
    
    this.vanitySlug = vanitySlug;
  }


  public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost targetUrl(String targetUrl) {
    
    
    
    
    this.targetUrl = targetUrl;
    return this;
  }

   /**
   * The new URL that the vanity link should redirect to.
   * @return targetUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The new URL that the vanity link should redirect to.")

  public String getTargetUrl() {
    return targetUrl;
  }


  public void setTargetUrl(String targetUrl) {
    
    
    
    this.targetUrl = targetUrl;
  }


  public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost comment(String comment) {
    
    
    
    
    this.comment = comment;
    return this;
  }

   /**
   * A new comment or description for the vanity link.
   * @return comment
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A new comment or description for the vanity link.")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    
    
    
    this.comment = comment;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost instance itself
   */
  public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost bodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost = (BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost) o;
    return Objects.equals(this.vanitySlug, bodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.vanitySlug) &&
        Objects.equals(this.targetUrl, bodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.targetUrl) &&
        Objects.equals(this.comment, bodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.comment)&&
        Objects.equals(this.additionalProperties, bodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vanitySlug, targetUrl, comment, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost {\n");
    sb.append("    vanitySlug: ").append(toIndentedString(vanitySlug)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("vanity_slug");
    openapiFields.add("target_url");
    openapiFields.add("comment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("vanity_slug");
    openapiRequiredFields.add("target_url");
    openapiRequiredFields.add("comment");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost is not found in the empty JSON string", BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("vanity_slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vanity_slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vanity_slug").toString()));
      }
      if (!jsonObj.get("target_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target_url").toString()));
      }
      if (!jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.class));

       return (TypeAdapter<T>) new TypeAdapter<BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost>() {
           @Override
           public void write(JsonWriter out, BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost
  * @throws IOException if the JSON string is invalid with respect to BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost
  */
  public static BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost.class);
  }

 /**
  * Convert an instance of BodyEditVanityLinkAdminN8enylacgdVanityLinkVanityLinkIdUpdatePost to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

