/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost {
  public static final String SERIALIZED_NAME_VOICE_NAME = "voice_name";
  @SerializedName(SERIALIZED_NAME_VOICE_NAME)
  private String voiceName;

  public static final String SERIALIZED_NAME_VOICE_DESCRIPTION = "voice_description";
  @SerializedName(SERIALIZED_NAME_VOICE_DESCRIPTION)
  private String voiceDescription;

  public static final String SERIALIZED_NAME_GENERATED_VOICE_ID = "generated_voice_id";
  @SerializedName(SERIALIZED_NAME_GENERATED_VOICE_ID)
  private String generatedVoiceId;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = null;

  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost() {
  }

  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost voiceName(String voiceName) {
    
    
    
    
    this.voiceName = voiceName;
    return this;
  }

   /**
   * Name to use for the created voice.
   * @return voiceName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name to use for the created voice.")

  public String getVoiceName() {
    return voiceName;
  }


  public void setVoiceName(String voiceName) {
    
    
    
    this.voiceName = voiceName;
  }


  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost voiceDescription(String voiceDescription) {
    
    
    
    
    this.voiceDescription = voiceDescription;
    return this;
  }

   /**
   * Description to use for the created voice.
   * @return voiceDescription
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Description to use for the created voice.")

  public String getVoiceDescription() {
    return voiceDescription;
  }


  public void setVoiceDescription(String voiceDescription) {
    
    
    
    this.voiceDescription = voiceDescription;
  }


  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost generatedVoiceId(String generatedVoiceId) {
    
    
    
    
    this.generatedVoiceId = generatedVoiceId;
    return this;
  }

   /**
   * The generated_voice_id to create, call POST /v1/voice-generation/generate-voice and fetch the generated_voice_id from the response header if don&#39;t have one yet.
   * @return generatedVoiceId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The generated_voice_id to create, call POST /v1/voice-generation/generate-voice and fetch the generated_voice_id from the response header if don't have one yet.")

  public String getGeneratedVoiceId() {
    return generatedVoiceId;
  }


  public void setGeneratedVoiceId(String generatedVoiceId) {
    
    
    
    this.generatedVoiceId = generatedVoiceId;
  }


  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost labels(Map<String, String> labels) {
    
    
    
    
    this.labels = labels;
    return this;
  }

  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * Optional, metadata to add to the created voice. Defaults to None.
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional, metadata to add to the created voice. Defaults to None.")

  public Map<String, String> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, String> labels) {
    
    
    
    this.labels = labels;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost instance itself
   */
  public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost = (BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost) o;
    return Objects.equals(this.voiceName, bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.voiceName) &&
        Objects.equals(this.voiceDescription, bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.voiceDescription) &&
        Objects.equals(this.generatedVoiceId, bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.generatedVoiceId) &&
        Objects.equals(this.labels, bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.labels)&&
        Objects.equals(this.additionalProperties, bodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voiceName, voiceDescription, generatedVoiceId, labels, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost {\n");
    sb.append("    voiceName: ").append(toIndentedString(voiceName)).append("\n");
    sb.append("    voiceDescription: ").append(toIndentedString(voiceDescription)).append("\n");
    sb.append("    generatedVoiceId: ").append(toIndentedString(generatedVoiceId)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("voice_name");
    openapiFields.add("voice_description");
    openapiFields.add("generated_voice_id");
    openapiFields.add("labels");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("voice_name");
    openapiRequiredFields.add("voice_description");
    openapiRequiredFields.add("generated_voice_id");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost is not found in the empty JSON string", BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("voice_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voice_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voice_name").toString()));
      }
      if (!jsonObj.get("voice_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voice_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voice_description").toString()));
      }
      if (!jsonObj.get("generated_voice_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `generated_voice_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("generated_voice_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.class));

       return (TypeAdapter<T>) new TypeAdapter<BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost>() {
           @Override
           public void write(JsonWriter out, BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
  * @throws IOException if the JSON string is invalid with respect to BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
  */
  public static BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost.class);
  }

 /**
  * Convert an instance of BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

