/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InvoiceResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ExtendedSubscriptionResponseModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExtendedSubscriptionResponseModel {
  public static final String SERIALIZED_NAME_TIER = "tier";
  @SerializedName(SERIALIZED_NAME_TIER)
  private String tier;

  public static final String SERIALIZED_NAME_CHARACTER_COUNT = "character_count";
  @SerializedName(SERIALIZED_NAME_CHARACTER_COUNT)
  private Integer characterCount;

  public static final String SERIALIZED_NAME_CHARACTER_LIMIT = "character_limit";
  @SerializedName(SERIALIZED_NAME_CHARACTER_LIMIT)
  private Integer characterLimit;

  public static final String SERIALIZED_NAME_CAN_EXTEND_CHARACTER_LIMIT = "can_extend_character_limit";
  @SerializedName(SERIALIZED_NAME_CAN_EXTEND_CHARACTER_LIMIT)
  private Boolean canExtendCharacterLimit;

  public static final String SERIALIZED_NAME_ALLOWED_TO_EXTEND_CHARACTER_LIMIT = "allowed_to_extend_character_limit";
  @SerializedName(SERIALIZED_NAME_ALLOWED_TO_EXTEND_CHARACTER_LIMIT)
  private Boolean allowedToExtendCharacterLimit;

  public static final String SERIALIZED_NAME_NEXT_CHARACTER_COUNT_RESET_UNIX = "next_character_count_reset_unix";
  @SerializedName(SERIALIZED_NAME_NEXT_CHARACTER_COUNT_RESET_UNIX)
  private Integer nextCharacterCountResetUnix;

  public static final String SERIALIZED_NAME_VOICE_LIMIT = "voice_limit";
  @SerializedName(SERIALIZED_NAME_VOICE_LIMIT)
  private Integer voiceLimit;

  public static final String SERIALIZED_NAME_MAX_VOICE_ADD_EDITS = "max_voice_add_edits";
  @SerializedName(SERIALIZED_NAME_MAX_VOICE_ADD_EDITS)
  private Integer maxVoiceAddEdits;

  public static final String SERIALIZED_NAME_VOICE_ADD_EDIT_COUNTER = "voice_add_edit_counter";
  @SerializedName(SERIALIZED_NAME_VOICE_ADD_EDIT_COUNTER)
  private Integer voiceAddEditCounter;

  public static final String SERIALIZED_NAME_PROFESSIONAL_VOICE_LIMIT = "professional_voice_limit";
  @SerializedName(SERIALIZED_NAME_PROFESSIONAL_VOICE_LIMIT)
  private Integer professionalVoiceLimit;

  public static final String SERIALIZED_NAME_CAN_EXTEND_VOICE_LIMIT = "can_extend_voice_limit";
  @SerializedName(SERIALIZED_NAME_CAN_EXTEND_VOICE_LIMIT)
  private Boolean canExtendVoiceLimit;

  public static final String SERIALIZED_NAME_CAN_USE_INSTANT_VOICE_CLONING = "can_use_instant_voice_cloning";
  @SerializedName(SERIALIZED_NAME_CAN_USE_INSTANT_VOICE_CLONING)
  private Boolean canUseInstantVoiceCloning;

  public static final String SERIALIZED_NAME_CAN_USE_PROFESSIONAL_VOICE_CLONING = "can_use_professional_voice_cloning";
  @SerializedName(SERIALIZED_NAME_CAN_USE_PROFESSIONAL_VOICE_CLONING)
  private Boolean canUseProfessionalVoiceCloning;

  /**
   * Gets or Sets currency
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
 public enum CurrencyEnum {
    USD("usd"),
    
    EUR("eur");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private CurrencyEnum currency;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
 public enum StatusEnum {
    TRIALING("trialing"),
    
    ACTIVE("active"),
    
    INCOMPLETE("incomplete"),
    
    INCOMPLETE_EXPIRED("incomplete_expired"),
    
    PAST_DUE("past_due"),
    
    CANCELED("canceled"),
    
    UNPAID("unpaid"),
    
    FREE("free");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_NEXT_INVOICE = "next_invoice";
  @SerializedName(SERIALIZED_NAME_NEXT_INVOICE)
  private InvoiceResponseModel nextInvoice;

  public static final String SERIALIZED_NAME_HAS_OPEN_INVOICES = "has_open_invoices";
  @SerializedName(SERIALIZED_NAME_HAS_OPEN_INVOICES)
  private Boolean hasOpenInvoices;

  public ExtendedSubscriptionResponseModel() {
  }

  public ExtendedSubscriptionResponseModel tier(String tier) {
    
    
    
    
    this.tier = tier;
    return this;
  }

   /**
   * Get tier
   * @return tier
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTier() {
    return tier;
  }


  public void setTier(String tier) {
    
    
    
    this.tier = tier;
  }


  public ExtendedSubscriptionResponseModel characterCount(Integer characterCount) {
    
    
    
    
    this.characterCount = characterCount;
    return this;
  }

   /**
   * Get characterCount
   * @return characterCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getCharacterCount() {
    return characterCount;
  }


  public void setCharacterCount(Integer characterCount) {
    
    
    
    this.characterCount = characterCount;
  }


  public ExtendedSubscriptionResponseModel characterLimit(Integer characterLimit) {
    
    
    
    
    this.characterLimit = characterLimit;
    return this;
  }

   /**
   * Get characterLimit
   * @return characterLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getCharacterLimit() {
    return characterLimit;
  }


  public void setCharacterLimit(Integer characterLimit) {
    
    
    
    this.characterLimit = characterLimit;
  }


  public ExtendedSubscriptionResponseModel canExtendCharacterLimit(Boolean canExtendCharacterLimit) {
    
    
    
    
    this.canExtendCharacterLimit = canExtendCharacterLimit;
    return this;
  }

   /**
   * Get canExtendCharacterLimit
   * @return canExtendCharacterLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getCanExtendCharacterLimit() {
    return canExtendCharacterLimit;
  }


  public void setCanExtendCharacterLimit(Boolean canExtendCharacterLimit) {
    
    
    
    this.canExtendCharacterLimit = canExtendCharacterLimit;
  }


  public ExtendedSubscriptionResponseModel allowedToExtendCharacterLimit(Boolean allowedToExtendCharacterLimit) {
    
    
    
    
    this.allowedToExtendCharacterLimit = allowedToExtendCharacterLimit;
    return this;
  }

   /**
   * Get allowedToExtendCharacterLimit
   * @return allowedToExtendCharacterLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getAllowedToExtendCharacterLimit() {
    return allowedToExtendCharacterLimit;
  }


  public void setAllowedToExtendCharacterLimit(Boolean allowedToExtendCharacterLimit) {
    
    
    
    this.allowedToExtendCharacterLimit = allowedToExtendCharacterLimit;
  }


  public ExtendedSubscriptionResponseModel nextCharacterCountResetUnix(Integer nextCharacterCountResetUnix) {
    
    
    
    
    this.nextCharacterCountResetUnix = nextCharacterCountResetUnix;
    return this;
  }

   /**
   * Get nextCharacterCountResetUnix
   * @return nextCharacterCountResetUnix
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getNextCharacterCountResetUnix() {
    return nextCharacterCountResetUnix;
  }


  public void setNextCharacterCountResetUnix(Integer nextCharacterCountResetUnix) {
    
    
    
    this.nextCharacterCountResetUnix = nextCharacterCountResetUnix;
  }


  public ExtendedSubscriptionResponseModel voiceLimit(Integer voiceLimit) {
    
    
    
    
    this.voiceLimit = voiceLimit;
    return this;
  }

   /**
   * Get voiceLimit
   * @return voiceLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getVoiceLimit() {
    return voiceLimit;
  }


  public void setVoiceLimit(Integer voiceLimit) {
    
    
    
    this.voiceLimit = voiceLimit;
  }


  public ExtendedSubscriptionResponseModel maxVoiceAddEdits(Integer maxVoiceAddEdits) {
    
    
    
    
    this.maxVoiceAddEdits = maxVoiceAddEdits;
    return this;
  }

   /**
   * Get maxVoiceAddEdits
   * @return maxVoiceAddEdits
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getMaxVoiceAddEdits() {
    return maxVoiceAddEdits;
  }


  public void setMaxVoiceAddEdits(Integer maxVoiceAddEdits) {
    
    
    
    this.maxVoiceAddEdits = maxVoiceAddEdits;
  }


  public ExtendedSubscriptionResponseModel voiceAddEditCounter(Integer voiceAddEditCounter) {
    
    
    
    
    this.voiceAddEditCounter = voiceAddEditCounter;
    return this;
  }

   /**
   * Get voiceAddEditCounter
   * @return voiceAddEditCounter
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getVoiceAddEditCounter() {
    return voiceAddEditCounter;
  }


  public void setVoiceAddEditCounter(Integer voiceAddEditCounter) {
    
    
    
    this.voiceAddEditCounter = voiceAddEditCounter;
  }


  public ExtendedSubscriptionResponseModel professionalVoiceLimit(Integer professionalVoiceLimit) {
    
    
    
    
    this.professionalVoiceLimit = professionalVoiceLimit;
    return this;
  }

   /**
   * Get professionalVoiceLimit
   * @return professionalVoiceLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getProfessionalVoiceLimit() {
    return professionalVoiceLimit;
  }


  public void setProfessionalVoiceLimit(Integer professionalVoiceLimit) {
    
    
    
    this.professionalVoiceLimit = professionalVoiceLimit;
  }


  public ExtendedSubscriptionResponseModel canExtendVoiceLimit(Boolean canExtendVoiceLimit) {
    
    
    
    
    this.canExtendVoiceLimit = canExtendVoiceLimit;
    return this;
  }

   /**
   * Get canExtendVoiceLimit
   * @return canExtendVoiceLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getCanExtendVoiceLimit() {
    return canExtendVoiceLimit;
  }


  public void setCanExtendVoiceLimit(Boolean canExtendVoiceLimit) {
    
    
    
    this.canExtendVoiceLimit = canExtendVoiceLimit;
  }


  public ExtendedSubscriptionResponseModel canUseInstantVoiceCloning(Boolean canUseInstantVoiceCloning) {
    
    
    
    
    this.canUseInstantVoiceCloning = canUseInstantVoiceCloning;
    return this;
  }

   /**
   * Get canUseInstantVoiceCloning
   * @return canUseInstantVoiceCloning
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getCanUseInstantVoiceCloning() {
    return canUseInstantVoiceCloning;
  }


  public void setCanUseInstantVoiceCloning(Boolean canUseInstantVoiceCloning) {
    
    
    
    this.canUseInstantVoiceCloning = canUseInstantVoiceCloning;
  }


  public ExtendedSubscriptionResponseModel canUseProfessionalVoiceCloning(Boolean canUseProfessionalVoiceCloning) {
    
    
    
    
    this.canUseProfessionalVoiceCloning = canUseProfessionalVoiceCloning;
    return this;
  }

   /**
   * Get canUseProfessionalVoiceCloning
   * @return canUseProfessionalVoiceCloning
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getCanUseProfessionalVoiceCloning() {
    return canUseProfessionalVoiceCloning;
  }


  public void setCanUseProfessionalVoiceCloning(Boolean canUseProfessionalVoiceCloning) {
    
    
    
    this.canUseProfessionalVoiceCloning = canUseProfessionalVoiceCloning;
  }


  public ExtendedSubscriptionResponseModel currency(CurrencyEnum currency) {
    
    
    
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public CurrencyEnum getCurrency() {
    return currency;
  }


  public void setCurrency(CurrencyEnum currency) {
    
    
    
    this.currency = currency;
  }


  public ExtendedSubscriptionResponseModel status(StatusEnum status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    
    
    
    this.status = status;
  }


  public ExtendedSubscriptionResponseModel nextInvoice(InvoiceResponseModel nextInvoice) {
    
    
    
    
    this.nextInvoice = nextInvoice;
    return this;
  }

   /**
   * Get nextInvoice
   * @return nextInvoice
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InvoiceResponseModel getNextInvoice() {
    return nextInvoice;
  }


  public void setNextInvoice(InvoiceResponseModel nextInvoice) {
    
    
    
    this.nextInvoice = nextInvoice;
  }


  public ExtendedSubscriptionResponseModel hasOpenInvoices(Boolean hasOpenInvoices) {
    
    
    
    
    this.hasOpenInvoices = hasOpenInvoices;
    return this;
  }

   /**
   * Get hasOpenInvoices
   * @return hasOpenInvoices
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasOpenInvoices() {
    return hasOpenInvoices;
  }


  public void setHasOpenInvoices(Boolean hasOpenInvoices) {
    
    
    
    this.hasOpenInvoices = hasOpenInvoices;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExtendedSubscriptionResponseModel instance itself
   */
  public ExtendedSubscriptionResponseModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtendedSubscriptionResponseModel extendedSubscriptionResponseModel = (ExtendedSubscriptionResponseModel) o;
    return Objects.equals(this.tier, extendedSubscriptionResponseModel.tier) &&
        Objects.equals(this.characterCount, extendedSubscriptionResponseModel.characterCount) &&
        Objects.equals(this.characterLimit, extendedSubscriptionResponseModel.characterLimit) &&
        Objects.equals(this.canExtendCharacterLimit, extendedSubscriptionResponseModel.canExtendCharacterLimit) &&
        Objects.equals(this.allowedToExtendCharacterLimit, extendedSubscriptionResponseModel.allowedToExtendCharacterLimit) &&
        Objects.equals(this.nextCharacterCountResetUnix, extendedSubscriptionResponseModel.nextCharacterCountResetUnix) &&
        Objects.equals(this.voiceLimit, extendedSubscriptionResponseModel.voiceLimit) &&
        Objects.equals(this.maxVoiceAddEdits, extendedSubscriptionResponseModel.maxVoiceAddEdits) &&
        Objects.equals(this.voiceAddEditCounter, extendedSubscriptionResponseModel.voiceAddEditCounter) &&
        Objects.equals(this.professionalVoiceLimit, extendedSubscriptionResponseModel.professionalVoiceLimit) &&
        Objects.equals(this.canExtendVoiceLimit, extendedSubscriptionResponseModel.canExtendVoiceLimit) &&
        Objects.equals(this.canUseInstantVoiceCloning, extendedSubscriptionResponseModel.canUseInstantVoiceCloning) &&
        Objects.equals(this.canUseProfessionalVoiceCloning, extendedSubscriptionResponseModel.canUseProfessionalVoiceCloning) &&
        Objects.equals(this.currency, extendedSubscriptionResponseModel.currency) &&
        Objects.equals(this.status, extendedSubscriptionResponseModel.status) &&
        Objects.equals(this.nextInvoice, extendedSubscriptionResponseModel.nextInvoice) &&
        Objects.equals(this.hasOpenInvoices, extendedSubscriptionResponseModel.hasOpenInvoices)&&
        Objects.equals(this.additionalProperties, extendedSubscriptionResponseModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tier, characterCount, characterLimit, canExtendCharacterLimit, allowedToExtendCharacterLimit, nextCharacterCountResetUnix, voiceLimit, maxVoiceAddEdits, voiceAddEditCounter, professionalVoiceLimit, canExtendVoiceLimit, canUseInstantVoiceCloning, canUseProfessionalVoiceCloning, currency, status, nextInvoice, hasOpenInvoices, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedSubscriptionResponseModel {\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    characterCount: ").append(toIndentedString(characterCount)).append("\n");
    sb.append("    characterLimit: ").append(toIndentedString(characterLimit)).append("\n");
    sb.append("    canExtendCharacterLimit: ").append(toIndentedString(canExtendCharacterLimit)).append("\n");
    sb.append("    allowedToExtendCharacterLimit: ").append(toIndentedString(allowedToExtendCharacterLimit)).append("\n");
    sb.append("    nextCharacterCountResetUnix: ").append(toIndentedString(nextCharacterCountResetUnix)).append("\n");
    sb.append("    voiceLimit: ").append(toIndentedString(voiceLimit)).append("\n");
    sb.append("    maxVoiceAddEdits: ").append(toIndentedString(maxVoiceAddEdits)).append("\n");
    sb.append("    voiceAddEditCounter: ").append(toIndentedString(voiceAddEditCounter)).append("\n");
    sb.append("    professionalVoiceLimit: ").append(toIndentedString(professionalVoiceLimit)).append("\n");
    sb.append("    canExtendVoiceLimit: ").append(toIndentedString(canExtendVoiceLimit)).append("\n");
    sb.append("    canUseInstantVoiceCloning: ").append(toIndentedString(canUseInstantVoiceCloning)).append("\n");
    sb.append("    canUseProfessionalVoiceCloning: ").append(toIndentedString(canUseProfessionalVoiceCloning)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    nextInvoice: ").append(toIndentedString(nextInvoice)).append("\n");
    sb.append("    hasOpenInvoices: ").append(toIndentedString(hasOpenInvoices)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tier");
    openapiFields.add("character_count");
    openapiFields.add("character_limit");
    openapiFields.add("can_extend_character_limit");
    openapiFields.add("allowed_to_extend_character_limit");
    openapiFields.add("next_character_count_reset_unix");
    openapiFields.add("voice_limit");
    openapiFields.add("max_voice_add_edits");
    openapiFields.add("voice_add_edit_counter");
    openapiFields.add("professional_voice_limit");
    openapiFields.add("can_extend_voice_limit");
    openapiFields.add("can_use_instant_voice_cloning");
    openapiFields.add("can_use_professional_voice_cloning");
    openapiFields.add("currency");
    openapiFields.add("status");
    openapiFields.add("next_invoice");
    openapiFields.add("has_open_invoices");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("tier");
    openapiRequiredFields.add("character_count");
    openapiRequiredFields.add("character_limit");
    openapiRequiredFields.add("can_extend_character_limit");
    openapiRequiredFields.add("allowed_to_extend_character_limit");
    openapiRequiredFields.add("next_character_count_reset_unix");
    openapiRequiredFields.add("voice_limit");
    openapiRequiredFields.add("max_voice_add_edits");
    openapiRequiredFields.add("voice_add_edit_counter");
    openapiRequiredFields.add("professional_voice_limit");
    openapiRequiredFields.add("can_extend_voice_limit");
    openapiRequiredFields.add("can_use_instant_voice_cloning");
    openapiRequiredFields.add("can_use_professional_voice_cloning");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("next_invoice");
    openapiRequiredFields.add("has_open_invoices");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExtendedSubscriptionResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExtendedSubscriptionResponseModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExtendedSubscriptionResponseModel is not found in the empty JSON string", ExtendedSubscriptionResponseModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExtendedSubscriptionResponseModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("tier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tier").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `next_invoice`
      InvoiceResponseModel.validateJsonObject(jsonObj.getAsJsonObject("next_invoice"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExtendedSubscriptionResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExtendedSubscriptionResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExtendedSubscriptionResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExtendedSubscriptionResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<ExtendedSubscriptionResponseModel>() {
           @Override
           public void write(JsonWriter out, ExtendedSubscriptionResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExtendedSubscriptionResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExtendedSubscriptionResponseModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExtendedSubscriptionResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExtendedSubscriptionResponseModel
  * @throws IOException if the JSON string is invalid with respect to ExtendedSubscriptionResponseModel
  */
  public static ExtendedSubscriptionResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExtendedSubscriptionResponseModel.class);
  }

 /**
  * Convert an instance of ExtendedSubscriptionResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

