/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LibraryVoiceResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GetLibraryVoicesResponseModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GetLibraryVoicesResponseModel {
  public static final String SERIALIZED_NAME_VOICES = "voices";
  @SerializedName(SERIALIZED_NAME_VOICES)
  private List<LibraryVoiceResponseModel> voices = new ArrayList<>();

  public static final String SERIALIZED_NAME_LAST_SORT_ID = "last_sort_id";
  @SerializedName(SERIALIZED_NAME_LAST_SORT_ID)
  private String lastSortId;

  public static final String SERIALIZED_NAME_HAS_MORE = "has_more";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  private Boolean hasMore;

  public GetLibraryVoicesResponseModel() {
  }

  public GetLibraryVoicesResponseModel voices(List<LibraryVoiceResponseModel> voices) {
    
    
    
    
    this.voices = voices;
    return this;
  }

  public GetLibraryVoicesResponseModel addVoicesItem(LibraryVoiceResponseModel voicesItem) {
    this.voices.add(voicesItem);
    return this;
  }

   /**
   * Get voices
   * @return voices
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<LibraryVoiceResponseModel> getVoices() {
    return voices;
  }


  public void setVoices(List<LibraryVoiceResponseModel> voices) {
    
    
    
    this.voices = voices;
  }


  public GetLibraryVoicesResponseModel lastSortId(String lastSortId) {
    
    
    
    
    this.lastSortId = lastSortId;
    return this;
  }

   /**
   * Get lastSortId
   * @return lastSortId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastSortId() {
    return lastSortId;
  }


  public void setLastSortId(String lastSortId) {
    
    
    
    this.lastSortId = lastSortId;
  }


  public GetLibraryVoicesResponseModel hasMore(Boolean hasMore) {
    
    
    
    
    this.hasMore = hasMore;
    return this;
  }

   /**
   * Get hasMore
   * @return hasMore
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getHasMore() {
    return hasMore;
  }


  public void setHasMore(Boolean hasMore) {
    
    
    
    this.hasMore = hasMore;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetLibraryVoicesResponseModel instance itself
   */
  public GetLibraryVoicesResponseModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLibraryVoicesResponseModel getLibraryVoicesResponseModel = (GetLibraryVoicesResponseModel) o;
    return Objects.equals(this.voices, getLibraryVoicesResponseModel.voices) &&
        Objects.equals(this.lastSortId, getLibraryVoicesResponseModel.lastSortId) &&
        Objects.equals(this.hasMore, getLibraryVoicesResponseModel.hasMore)&&
        Objects.equals(this.additionalProperties, getLibraryVoicesResponseModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voices, lastSortId, hasMore, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLibraryVoicesResponseModel {\n");
    sb.append("    voices: ").append(toIndentedString(voices)).append("\n");
    sb.append("    lastSortId: ").append(toIndentedString(lastSortId)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("voices");
    openapiFields.add("last_sort_id");
    openapiFields.add("has_more");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("voices");
    openapiRequiredFields.add("last_sort_id");
    openapiRequiredFields.add("has_more");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetLibraryVoicesResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GetLibraryVoicesResponseModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetLibraryVoicesResponseModel is not found in the empty JSON string", GetLibraryVoicesResponseModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetLibraryVoicesResponseModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("voices").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `voices` to be an array in the JSON string but got `%s`", jsonObj.get("voices").toString()));
      }

      JsonArray jsonArrayvoices = jsonObj.getAsJsonArray("voices");
      // validate the required field `voices` (array)
      for (int i = 0; i < jsonArrayvoices.size(); i++) {
        LibraryVoiceResponseModel.validateJsonObject(jsonArrayvoices.get(i).getAsJsonObject());
      };
      if (!jsonObj.get("last_sort_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_sort_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_sort_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetLibraryVoicesResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetLibraryVoicesResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetLibraryVoicesResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetLibraryVoicesResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<GetLibraryVoicesResponseModel>() {
           @Override
           public void write(JsonWriter out, GetLibraryVoicesResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetLibraryVoicesResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GetLibraryVoicesResponseModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetLibraryVoicesResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetLibraryVoicesResponseModel
  * @throws IOException if the JSON string is invalid with respect to GetLibraryVoicesResponseModel
  */
  public static GetLibraryVoicesResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetLibraryVoicesResponseModel.class);
  }

 /**
  * Convert an instance of GetLibraryVoicesResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

