/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VoiceGenerationParameterOptionResponseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * VoiceGenerationParameterResponseModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class VoiceGenerationParameterResponseModel {
  public static final String SERIALIZED_NAME_GENDERS = "genders";
  @SerializedName(SERIALIZED_NAME_GENDERS)
  private List<VoiceGenerationParameterOptionResponseModel> genders = new ArrayList<>();

  public static final String SERIALIZED_NAME_ACCENTS = "accents";
  @SerializedName(SERIALIZED_NAME_ACCENTS)
  private List<VoiceGenerationParameterOptionResponseModel> accents = new ArrayList<>();

  public static final String SERIALIZED_NAME_AGES = "ages";
  @SerializedName(SERIALIZED_NAME_AGES)
  private List<VoiceGenerationParameterOptionResponseModel> ages = new ArrayList<>();

  public static final String SERIALIZED_NAME_MINIMUM_CHARACTERS = "minimum_characters";
  @SerializedName(SERIALIZED_NAME_MINIMUM_CHARACTERS)
  private Integer minimumCharacters;

  public static final String SERIALIZED_NAME_MAXIMUM_CHARACTERS = "maximum_characters";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_CHARACTERS)
  private Integer maximumCharacters;

  public static final String SERIALIZED_NAME_MINIMUM_ACCENT_STRENGTH = "minimum_accent_strength";
  @SerializedName(SERIALIZED_NAME_MINIMUM_ACCENT_STRENGTH)
  private Double minimumAccentStrength;

  public static final String SERIALIZED_NAME_MAXIMUM_ACCENT_STRENGTH = "maximum_accent_strength";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_ACCENT_STRENGTH)
  private Double maximumAccentStrength;

  public VoiceGenerationParameterResponseModel() {
  }

  public VoiceGenerationParameterResponseModel genders(List<VoiceGenerationParameterOptionResponseModel> genders) {
    
    
    
    
    this.genders = genders;
    return this;
  }

  public VoiceGenerationParameterResponseModel addGendersItem(VoiceGenerationParameterOptionResponseModel gendersItem) {
    this.genders.add(gendersItem);
    return this;
  }

   /**
   * Get genders
   * @return genders
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<VoiceGenerationParameterOptionResponseModel> getGenders() {
    return genders;
  }


  public void setGenders(List<VoiceGenerationParameterOptionResponseModel> genders) {
    
    
    
    this.genders = genders;
  }


  public VoiceGenerationParameterResponseModel accents(List<VoiceGenerationParameterOptionResponseModel> accents) {
    
    
    
    
    this.accents = accents;
    return this;
  }

  public VoiceGenerationParameterResponseModel addAccentsItem(VoiceGenerationParameterOptionResponseModel accentsItem) {
    this.accents.add(accentsItem);
    return this;
  }

   /**
   * Get accents
   * @return accents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<VoiceGenerationParameterOptionResponseModel> getAccents() {
    return accents;
  }


  public void setAccents(List<VoiceGenerationParameterOptionResponseModel> accents) {
    
    
    
    this.accents = accents;
  }


  public VoiceGenerationParameterResponseModel ages(List<VoiceGenerationParameterOptionResponseModel> ages) {
    
    
    
    
    this.ages = ages;
    return this;
  }

  public VoiceGenerationParameterResponseModel addAgesItem(VoiceGenerationParameterOptionResponseModel agesItem) {
    this.ages.add(agesItem);
    return this;
  }

   /**
   * Get ages
   * @return ages
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<VoiceGenerationParameterOptionResponseModel> getAges() {
    return ages;
  }


  public void setAges(List<VoiceGenerationParameterOptionResponseModel> ages) {
    
    
    
    this.ages = ages;
  }


  public VoiceGenerationParameterResponseModel minimumCharacters(Integer minimumCharacters) {
    
    
    
    
    this.minimumCharacters = minimumCharacters;
    return this;
  }

   /**
   * Get minimumCharacters
   * @return minimumCharacters
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getMinimumCharacters() {
    return minimumCharacters;
  }


  public void setMinimumCharacters(Integer minimumCharacters) {
    
    
    
    this.minimumCharacters = minimumCharacters;
  }


  public VoiceGenerationParameterResponseModel maximumCharacters(Integer maximumCharacters) {
    
    
    
    
    this.maximumCharacters = maximumCharacters;
    return this;
  }

   /**
   * Get maximumCharacters
   * @return maximumCharacters
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getMaximumCharacters() {
    return maximumCharacters;
  }


  public void setMaximumCharacters(Integer maximumCharacters) {
    
    
    
    this.maximumCharacters = maximumCharacters;
  }


  public VoiceGenerationParameterResponseModel minimumAccentStrength(Double minimumAccentStrength) {
    
    
    
    
    this.minimumAccentStrength = minimumAccentStrength;
    return this;
  }

  public VoiceGenerationParameterResponseModel minimumAccentStrength(Integer minimumAccentStrength) {
    
    
    
    
    this.minimumAccentStrength = minimumAccentStrength.doubleValue();
    return this;
  }

   /**
   * Get minimumAccentStrength
   * @return minimumAccentStrength
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getMinimumAccentStrength() {
    return minimumAccentStrength;
  }


  public void setMinimumAccentStrength(Double minimumAccentStrength) {
    
    
    
    this.minimumAccentStrength = minimumAccentStrength;
  }


  public VoiceGenerationParameterResponseModel maximumAccentStrength(Double maximumAccentStrength) {
    
    
    
    
    this.maximumAccentStrength = maximumAccentStrength;
    return this;
  }

  public VoiceGenerationParameterResponseModel maximumAccentStrength(Integer maximumAccentStrength) {
    
    
    
    
    this.maximumAccentStrength = maximumAccentStrength.doubleValue();
    return this;
  }

   /**
   * Get maximumAccentStrength
   * @return maximumAccentStrength
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getMaximumAccentStrength() {
    return maximumAccentStrength;
  }


  public void setMaximumAccentStrength(Double maximumAccentStrength) {
    
    
    
    this.maximumAccentStrength = maximumAccentStrength;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the VoiceGenerationParameterResponseModel instance itself
   */
  public VoiceGenerationParameterResponseModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoiceGenerationParameterResponseModel voiceGenerationParameterResponseModel = (VoiceGenerationParameterResponseModel) o;
    return Objects.equals(this.genders, voiceGenerationParameterResponseModel.genders) &&
        Objects.equals(this.accents, voiceGenerationParameterResponseModel.accents) &&
        Objects.equals(this.ages, voiceGenerationParameterResponseModel.ages) &&
        Objects.equals(this.minimumCharacters, voiceGenerationParameterResponseModel.minimumCharacters) &&
        Objects.equals(this.maximumCharacters, voiceGenerationParameterResponseModel.maximumCharacters) &&
        Objects.equals(this.minimumAccentStrength, voiceGenerationParameterResponseModel.minimumAccentStrength) &&
        Objects.equals(this.maximumAccentStrength, voiceGenerationParameterResponseModel.maximumAccentStrength)&&
        Objects.equals(this.additionalProperties, voiceGenerationParameterResponseModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genders, accents, ages, minimumCharacters, maximumCharacters, minimumAccentStrength, maximumAccentStrength, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoiceGenerationParameterResponseModel {\n");
    sb.append("    genders: ").append(toIndentedString(genders)).append("\n");
    sb.append("    accents: ").append(toIndentedString(accents)).append("\n");
    sb.append("    ages: ").append(toIndentedString(ages)).append("\n");
    sb.append("    minimumCharacters: ").append(toIndentedString(minimumCharacters)).append("\n");
    sb.append("    maximumCharacters: ").append(toIndentedString(maximumCharacters)).append("\n");
    sb.append("    minimumAccentStrength: ").append(toIndentedString(minimumAccentStrength)).append("\n");
    sb.append("    maximumAccentStrength: ").append(toIndentedString(maximumAccentStrength)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("genders");
    openapiFields.add("accents");
    openapiFields.add("ages");
    openapiFields.add("minimum_characters");
    openapiFields.add("maximum_characters");
    openapiFields.add("minimum_accent_strength");
    openapiFields.add("maximum_accent_strength");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("genders");
    openapiRequiredFields.add("accents");
    openapiRequiredFields.add("ages");
    openapiRequiredFields.add("minimum_characters");
    openapiRequiredFields.add("maximum_characters");
    openapiRequiredFields.add("minimum_accent_strength");
    openapiRequiredFields.add("maximum_accent_strength");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VoiceGenerationParameterResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!VoiceGenerationParameterResponseModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VoiceGenerationParameterResponseModel is not found in the empty JSON string", VoiceGenerationParameterResponseModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VoiceGenerationParameterResponseModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("genders").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `genders` to be an array in the JSON string but got `%s`", jsonObj.get("genders").toString()));
      }

      JsonArray jsonArraygenders = jsonObj.getAsJsonArray("genders");
      // validate the required field `genders` (array)
      for (int i = 0; i < jsonArraygenders.size(); i++) {
        VoiceGenerationParameterOptionResponseModel.validateJsonObject(jsonArraygenders.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("accents").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `accents` to be an array in the JSON string but got `%s`", jsonObj.get("accents").toString()));
      }

      JsonArray jsonArrayaccents = jsonObj.getAsJsonArray("accents");
      // validate the required field `accents` (array)
      for (int i = 0; i < jsonArrayaccents.size(); i++) {
        VoiceGenerationParameterOptionResponseModel.validateJsonObject(jsonArrayaccents.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("ages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `ages` to be an array in the JSON string but got `%s`", jsonObj.get("ages").toString()));
      }

      JsonArray jsonArrayages = jsonObj.getAsJsonArray("ages");
      // validate the required field `ages` (array)
      for (int i = 0; i < jsonArrayages.size(); i++) {
        VoiceGenerationParameterOptionResponseModel.validateJsonObject(jsonArrayages.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VoiceGenerationParameterResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VoiceGenerationParameterResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VoiceGenerationParameterResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VoiceGenerationParameterResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<VoiceGenerationParameterResponseModel>() {
           @Override
           public void write(JsonWriter out, VoiceGenerationParameterResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public VoiceGenerationParameterResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             VoiceGenerationParameterResponseModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VoiceGenerationParameterResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VoiceGenerationParameterResponseModel
  * @throws IOException if the JSON string is invalid with respect to VoiceGenerationParameterResponseModel
  */
  public static VoiceGenerationParameterResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VoiceGenerationParameterResponseModel.class);
  }

 /**
  * Convert an instance of VoiceGenerationParameterResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

