/*
 * ElevenLabs API Documentation
 * This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost;
import com.konfigthis.client.model.BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost;
import com.konfigthis.client.model.VoiceGenerationParameterResponseModel;
import com.konfigthis.client.model.VoiceResponseModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VoiceGenerationApi
 */
@Disabled
public class VoiceGenerationApiTest {

    private static VoiceGenerationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new VoiceGenerationApi(apiClient);
    }

    /**
     * Create A Previously Generated Voice
     *
     * Create a previously generated voice. This endpoint should be called after you fetched a generated_voice_id using /v1/voice-generation/generate-voice.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVoiceTest() throws ApiException {
        String voiceName = null;
        String voiceDescription = null;
        String generatedVoiceId = null;
        Map<String, String> labels = null;
        String xiApiKey = null;
        VoiceResponseModel response = api.createVoice(voiceName, voiceDescription, generatedVoiceId)
                .labels(labels)
                .xiApiKey(xiApiKey)
                .execute();
        // TODO: test validations
    }

    /**
     * Generate A Random Voice
     *
     * Generate a random voice based on parameters. This method returns a generated_voice_id in the response header, and a sample of the voice in the body. If you like the generated voice call /v1/voice-generation/create-voice with the generated_voice_id to create the voice.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateRandomVoiceTest() throws ApiException {
        String gender = null;
        String accent = null;
        String age = null;
        Double accentStrength = null;
        String text = null;
        String xiApiKey = null;
        api.generateRandomVoice(gender, accent, age, accentStrength, text)
                .xiApiKey(xiApiKey)
                .execute();
        // TODO: test validations
    }

    /**
     * Voice Generation Parameters
     *
     * Get possible parameters for the /v1/voice-generation/generate-voice endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVoiceGenerationParametersTest() throws ApiException {
        VoiceGenerationParameterResponseModel response = api.getVoiceGenerationParameters()
                .execute();
        // TODO: test validations
    }

}
